#  Install Scrapy and associated libraries

#  Version 0.1

FROM 		johnsn/pip
MAINTAINER	Nicholas Johns "nicholas.a.johns5@gmail.com"

RUN		apt-get update
RUN		apt-get install -y -q libxml2-dev
RUN		apt-get install -y -q libxslt1-dev

RUN		pip install Scrapy
