#  Install Python 2.7
#  Specificallt Install Python, dev, gcc and openssl
#  Version 0.1

FROM 		ubuntu
MAINTAINER	Nicholas Johns "nicholas.a.johns5@gmail.com"

RUN		apt-get update
RUN		apt-get install -y -q python2.7 python2.7-dev gcc openssl
